### ISSUE TITLE
FAQ tab?

### ISSUE THREAD

**Issue by bern** [UFSEC/SwampHacks#3]
What is SwampHacks?
- SwampHacks is an 18-hour hackathon hosted by the University of Florida's ACM student chapter, the UF Software Development Club, and Women in Computer Science Engineering. What is a hackathon? A hackathon is a team-based competition where the only objective is to make something awesome. Looking to make the next killer Android app? Have a great idea for a web application? Hackathons are an awesome fit for you.

Who can attend?
- Any university student in the world can hack with us. All we ask is that you sign up with a valid .edu email addresses. If you have a special situation and still want to attend SwampHacks, feel free to email us at swamphacks@gmail.com .

How much does it cost?
- SwampHacks - including all food, swag, and prizes - will be absolutely free! All we ask is that you bring an appetite for creation and innovation.

What should I bring with me?
- SwampHacks will run overnight, so bring some pajamas if you're so inclined! Other that that, bring your gear and a few energy drinks. We'll take care of the rest.

Do I have to stay the whole time?
- We won't lock you in, but please only hack at the competition. Feel free to go home and recharge if you need to.

Can I work on pre-existing projects?
- No. All competition items at SwampHacks must be started after the beginning of the event. Feel free to discuss ideas beforehand, though!

Can I compete in a team?
- Definitely! Teams (of no more than 5, please) are strongly encouraged. This way, those with a non-technical background can collaborate with rockstar programmers to make their incredible vision a reality. Teams will be formed at the event, so you can come alone and join a team once we start up.

**Comment by andrewvora** [comment]
Added as modal, accessible from the bottom.

**Comment by bern** [comment]
Sorry, can you change the email for "Who can attend" to info@swamphacks.com ?

**Comment by andrewvora** [comment]
Yeah, no problem. Should I change that for the sponsor contact email, too?

**Comment by nicktardif** [comment]
Oh yeah and we also own sponsors@swamphacks.com

**Comment by andrewvora** [comment]
Done.
